name: Test with Platformio

on: [push, pull_request]

jobs:
  build:

    container: ghcr.io/bertmelis/pio-test-container

    steps:
      - uses: actions/checkout@v4
      - name: Test
        run: |
          pio test -e native -v